# Generated by Django 6.0.4 on 2026-05-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracaouser',
            name='is_certifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='is_eu_importer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='is_exporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracaouser',
            name='is_government',
            field=models.BooleanField(default=False),
        ),
    ]
