# Generated by Django 6.0.4 on 2026-05-01 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tracaouser_is_certifier_tracaouser_is_eu_importer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='kyc_documents/front/', verbose_name="Carte d'identité (Recto)")),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='kyc_documents/back/', verbose_name="Carte d'identité (Verso)")),
                ('selfie_photo', models.ImageField(blank=True, null=True, upload_to='kyc_documents/selfie/', verbose_name='Selfie avec la carte')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut KYC')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
