# Generated by Django 6.0.4 on 2026-05-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_kycdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='id_picture',
        ),
    ]
