# Generated by Django 6.0.4 on 2026-05-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('product_type', models.CharField(choices=[('cacao', 'Cacao'), ('cafe', 'Cafe')], max_length=100)),
                ('species', models.TextField(blank=True, null=True)),
                ('origin', models.CharField(max_length=200)),
                ('surface_size', models.FloatField()),
                ('production_size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockTransporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
