# Generated by Django 6.0.4 on 2026-05-01 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockorigin',
            name='cooperative',
            field=models.ForeignKey(limit_choices_to={'is_cooperative_source': True}, on_delete=django.db.models.deletion.CASCADE, related_name='origin_stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockproducer',
            name='cooperative',
            field=models.ForeignKey(limit_choices_to={'is_cooperative_source': True}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_source_stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockproducer',
            name='producer',
            field=models.ForeignKey(limit_choices_to={'is_producer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='producer_stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockorigin',
            name='producer_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_records', to='stock.stockproducer'),
        ),
        migrations.AddField(
            model_name='stocktransporter',
            name='cooperative',
            field=models.ForeignKey(limit_choices_to={'is_cooperative_destination': True}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_destination_transports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransporter',
            name='stock_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_records', to='stock.stockorigin'),
        ),
        migrations.AddField(
            model_name='stocktransporter',
            name='transporter',
            field=models.ForeignKey(limit_choices_to={'is_transporter': True}, on_delete=django.db.models.deletion.CASCADE, related_name='transported_stocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
