# Generated by Django 6.0.4 on 2026-05-01 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproducer',
            name='origin',
            field=models.CharField(blank=True, help_text='Région ou village', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stockproducer',
            name='production_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockproducer',
            name='surface_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du champ ou de la plantation', max_length=255)),
                ('polygon_coordinates', models.JSONField(help_text="Liste des coordonnées GPS formant le contour du champ [{'lat': X, 'lng': Y}, ...]")),
                ('area_hectares', models.FloatField(blank=True, help_text='Surface estimée en hectares', null=True)),
                ('is_verified_by_coop', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(limit_choices_to={'is_producer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'is_cooperative_source': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stockproducer',
            name='farm',
            field=models.ForeignKey(blank=True, help_text="Le champ spécifique (polygone GPS) d'où provient la récolte.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='stock.farm'),
        ),
    ]
