# Generated by Django 6.0.4 on 2026-05-01 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockproducer_origin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exporter', models.ForeignKey(limit_choices_to={'is_exporter': True}, on_delete=django.db.models.deletion.CASCADE, related_name='received_export_stocks', to=settings.AUTH_USER_MODEL)),
                ('stock_transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_records', to='stock.stocktransporter')),
                ('transporter', models.ForeignKey(limit_choices_to={'is_transporter': True}, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
